{
    "title" : "hockey stick",
    "price" : "12.00",
    "title_city" : "Carson",
    "postal_code" : "90810",
    "description" : "its cool",
    "make" : "stick1",
    "model": "hard stick",
    "size": "L",
    "condition_description" : "yes buy this stick",
    "language": "English",
    "cryptocurrency_ok": 1,
    "delivery_ok": 1,
    "email": "g@gmail.com",
    "show_phone_number": 1,
    "phone_calls_ok": 1,
    "text_sms_ok": 1,
    "phone_number": "123-123-1231",
    "extension": "1222",
    "contact_name": "Matt",
    "show_address": 1,
    "street": "Main st",
    "cross_street": "South st",
    "city": "Long Beach",
    "item_image_url_https": "html",
    "url": "html",
    "category_id": 1,
    "user_id": 1
}